### ISSUE TITLE
how to run tailwindcss lsp in vue files

### ISSUE THREAD

**Issue by nour-dev** [merrickluo/lsp-tailwindcss#37] opened 2022-03-22 17:53 UTC
hey, 
I use emacs doom to develop web apps with vuejs. my setup is:
- web-mode (for syntax highlight + html autocompelte)
- lsp (+ [volar lsp](https://github.com/jadestrong/lsp-volar) )

for example I use vue Single File component like:
```vue
<template>
   <!-- auto complete class names in class="" -->
   <div class="">
       {{ name }} <br />
      <!-- auto complete class names in class="" -->
      <input v-model="name" class="" />
   </div>
</template>
<script lang="ts" setup>
let name = ref('');
</script>
``` 

my installation process for tailwindcss and volar in emacs doom:
```elisp
;; package.el
(package! lsp-volar :recipe (:host github :repo "jadestrong/lsp-volar"))
(package! lsp-tailwindcss :recipe (:host github :repo "merrickluo/lsp-tailwindcss"))

;; config.el
(use-package! lsp-volar)
(use-package! lsp-tailwindcss
  :init
  (setq lsp-tailwindcss-add-on-mode t))

(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))
(add-to-list 'lsp-language-id-configuration '(".*\\.vue$" . "web"))
```
- I want to use tailwindcss beside volar lsp server
- I want to autocomplete classes when write inside class value in html or any string in vue file

how to do it ?

thank you.

**Comment by merrickluo** [comment] 2022-03-24 03:52
I haven't tried using it in vue files yet, but here are some debug step you can try
1. did you install the language server itself? you can try `M-x lsp-install-server` and select `tailwindcss`
2. run `M-x lsp-describe-sessions` see if lsp-tailwindcss is running
3. run `M-x lsp-workspace-show-log` to see if there is any errors

**Comment by VisionaryAppDev** [comment] 2022-04-24 06:45
Hello @nour-dev,

I have tried this package recently and it's working pretty well on my Nuxt 3 project, although drop-down completion it's a little slower than my experience using Webstorm. Maybe there is some configuration for the delay here.

Currently, I am using latest Emacs 29.0.50 build from source with gcc (native-comp) and Doom Emacs. I am also using lsp-mode. I have some server install like you did such as eslint, vola and vls. I did install both because vola doesn't work with my Nuxt 3 but vls does. 

Here is my setup: 
- config.el
```
(straight-use-package
 '(lsp-tailwindcss :type git :host github :repo "merrickluo/lsp-tailwindcss"))

(use-package! lsp-tailwindcss)
```

- package.el
```
(package! lsp-tailwindcss :recipe (:host github :repo "merrickluo/lsp-tailwindcss"))
```

- install language server
```
sudo npm install -g @tailwindcss/language-server
```
 
That's all and it's working. But I am not sure if I place all the config in the right place. Especially for `(straight-use-package
 '(lsp-tailwindcss :type git :host github :repo "merrickluo/lsp-tailwindcss"))`. Is it needed to put in `straight.el` or in the package.el since the README is a little confusing here. Maybe @merrickluo  could help clarify.


![image](https://user-images.githubusercontent.com/27724011/164960383-53991a59-eb12-4ddb-a492-78ff6c4c1354.png)

**Comment by VisionaryAppDev** [comment] 2022-04-24 06:49
By the way, there is some problem with the completion here.  Any class start with `sm:`, `lg:`,  `md:` ...  won't show the completion. Not sure if it is really the how it is.

**Comment by merrickluo** [comment] 2022-04-26 08:36
@VisionaryAppDev you should only need to use `packages.el`. it's how you add your custom packages in doom emacs. The `straight-use-package` is for others doesn't use doom emacs. And since the package is in mepla now, it should work with just use-package too.

If `:` doesn't trigger completion, it might be a conflict between `company-mode` and the language server, I'll look into that.

**Comment by merrickluo** [comment] 2022-04-26 13:45
![圖片](https://user-images.githubusercontent.com/1495875/165313709-34ed0e6b-19e5-41a7-8f33-45af61d6eccb.png)

I can't seem to reproduce the completion problem you are having, Is something particular about your setup?

**Comment by VisionaryAppDev** [comment] 2022-04-28 04:31
Helllo @merrickluo,

> The straight-use-package is for others doesn't use doom emacs.

Isn't straight suppose to be used by doom user? I saw doom emacs mentions that they are powered by straight.el on their github homepage.

**Comment by VisionaryAppDev** [comment] 2022-04-28 04:48
I have Emacs and Doom latest version reinstall on my other machine and everything including `sm: md: lg:...` working as expected but i need to call M-x lsp multiple times and wait for a while before the completion show up. In some occasion, tailwind-lsp-server exit expected and require to restart while using.

By the way, on my other machine, completion seem too slow. I have the same language server on vscode and it is a lot more faster tbh.

https://user-images.githubusercontent.com/27724011/165676978-da72b0a2-22df-4e42-be0b-2153ec18bde6.mp4

**Comment by merrickluo** [comment] 2022-04-29 05:49
> Isn't straight suppose to be used by doom user? I saw doom emacs mentions that they are powered by straight.el on their github homepage.

yes, that's the `(package! lsp-tailwindcss)` macro do, basically this macro will expand to
```emacs-lisp
(straight-use-package
 '(lsp-tailwindcss :type git :host github :repo "merrickluo/lsp-tailwindcss"))
```
it's more complicated than this, but you get the idea.

The slowness you are experiencing is basically a emacs/lsp-mode problem, we only got one thread to run lisp code :( , so there is nothing I can do about that.

**Comment by VisionaryAppDev** [comment] 2022-05-03 06:42
Hello @merrickluo,

I have run profiler and found the following result and not sure if it's useful. 

![image](https://user-images.githubusercontent.com/27724011/166413171-4c4086e1-1b35-431c-b5b8-c35c717a9de2.png)

> we only got one thread to run lisp code :( , so there is nothing I can do about that.

Is that so? But I saw lsp mode claim that their performance is comparable to vscode. :(

**Comment by merrickluo** [comment] 2022-05-05 14:15
Hi @VisionaryAppDev, your screenshot suggests most time spent is in `lsp-mode` sending requests to the server. This package is no more than a glue between `lsp-mode` and `tailwindcss-language-server`, it has nothing to do with performance. I suggest you open a ticket in `lsp-mode` for the performance issue.

Closing this issue since it should be configuration problems.

**Closed by merrickluo** 2022-05-05 14:15 UTC
